### ISSUE TITLE
Tours nav item broken when Curatescape is not the default theme

### ISSUE THREAD

**Issue by JMarchesoni** [CPHDH/Curatescape#50]
The Tours nav item shows up on the main site, but goes to a 404 page not found error unless the Curatescape theme is set as the site theme. This is a problem for us since we only want to use the Curatescape theme on certain exhibits.

I've tried adding a simple page for tours but it still goes to a 404 error.

**Comment by csudigitalhumanities** [comment]
Hi! This is because the Tour Builder plugin isn't distributed with default display templates. It just uses the templates in the Curatescape theme, which usually works fine since the Tour Builder plugin is generally only used on Curatescape sites. That said, it's probably time to address this and make the plugin more broadly compatible. No timeline yet but stay tuned.

**Comment by ebellempire** [comment]
Hi @JMarchesoni ,

I've added default templates for non-curatescape themes. 

You can check out the latest version of the plugin at:
https://github.com/CPHDH/TourBuilder

Commit details:
https://github.com/CPHDH/TourBuilder/commit/6084a46983290d844d6f70d3b390d39bc791ae66

To customize the plugin for your theme, copy all files from `plugins/TourBuilder/views/public/tours` into a new directory in your theme called `tour-builder/tours`. From there, you can safely tweak the styles and functionality, though it should work fine out of the box.

**Comment by JMarchesoni** [comment]
Thank you!
